### ISSUE TITLE
Option for a secondary logo input to go in the footer

### ISSUE THREAD

**Issue by damiaanmelis** [smallaxeorg/ActionNetwork#3]
Realistically in a lot of cases we'll need to use a reversed or alternative logo in the footer.
![Screenshot 2021-09-30 at 15 32 18](https://user-images.githubusercontent.com/25006829/135475290-7e30da58-1733-4503-a972-6c0b0d1795c1.png)

**Comment by hwbhurd** [comment]
@damiaanmelis you should be able to do this one already, just put a different URL for the logo in the footer tab than you do for the header

**Comment by damiaanmelis** [comment]
> @damiaanmelis you should be able to do this one already, just put a different URL for the logo in the footer tab than you do for the header

Doh! Yes that's my bad!
